import type { BulkUser, RawUser } from '@/types/share'
import fetch from 'cross-fetch'
import crypto from 'crypto'

export class Logger {
  printFormat: string

  constructor() {
    this.printFormat = '[%s] %s'
  }

  print(status: string, str: string): void {
    console.log(`\x1b[37m${this.printFormat}\x1b[0m`, status, str)
  }

  error(err: unknown): void {
    console.error(`\x1b[31m${this.printFormat}\x1b[0m`, 'ERROR', err)
  }
}

export class UserSource {
  private API_LIMIT = 5000
  private fetchURL = 'https://randomuser.me/api/?password=upper,lower,number,6-18&inc=gender,name,email,picture,login,dob'

  generatedCount: number
  seed: string
  logger: Logger

  constructor(seed: string, logger: Logger) {
    this.generatedCount = 0
    this.seed = seed
    this.logger = logger
  }

  reset(): void {
    this.generatedCount = 0
  }

  setSeed(seed: string): void {
    this.seed = seed
  }

  async get(count: number): Promise<{
    status: 'success' | 'failed';
    data: BulkUser[]
  }> {
    // use generatedCount to keep generated users count,
    // so when getting users by count, the return result could be unique
    count = Math.min(Math.max(0, count), this.API_LIMIT)
    const page = Math.ceil(this.generatedCount / count) + 1 // 1 based index
    const url = `${this.fetchURL}&seed=${this.seed}&results=${count}&page=${page}`

    try {
      let response = await fetch(url)

      const users = await response.json()

      /*
        the hash result from randomuser.me is generated by (password + salt)
        while the hash validation on firebase is (salt + password)
        ref:
          https://github.com/firebase/firebase-admin-node/issues/792#issuecomment-589986897
          https://github.com/RandomAPI/Randomuser.me-Node/blob/64fd050d99e1242a9bf219810bc54ecbdc1d76fb/api/1.3/api.js#L184
      */
      const data = users.results.map((user: RawUser): BulkUser => ({
        uid: user.email,
        email: user.email,
        passwordHash: crypto.createHash('sha256').update(`${user.login.salt}${user.login.password}`).digest(),
        passwordSalt: Buffer.from(user.login.salt),
        name: `${user.name.first} ${user.name.last}`,
        age: user.dob.age,
        avatar: user.picture.large,
        gender: user.gender
      }))

      return {
        status: 'success',
        data
      }

    } catch (error) {
      this.logger.error(error)

      return {
        status: 'failed',
        data: []
      }
    } finally {
      this.generatedCount += count
    }
  }
}